### PR TITLE
Latent Behaviors in Formation

### PR DESCRIPTION
**Pull request by JNeiger**
## Description
Partial implementation of formations. For right now this just means the basic latent behaviors and the setup of positions.

TODO:
- [X] Clean up center code

## Associated Issue
Issue #1334 partial

## Design Documents
[Link](https://docs.google.com/document/d/1YvTT1JhMt96bAyG10OOBN2x2l5xSfB9hDgA5_lJJ20E/edit#)

### CODE REVIEW

**Comment by JNeiger** [comment]
Not sure how to set this up as a draft while I make the final fixes

**Comment by oswinso** [comment]
I think when creating the PR instead of clicking the "Create pull request" button you can click the dropdown and do "Create draft pull request" and that will do it

**Comment by JNeiger** [comment]
Meh, thats too much effort to fix. Close enough

**Comment by kylestach** [comment]
This is looking pretty good, I'm very excited about this. My one question involves how you pull robots out of formation - are they just a lower priority in role assignment/things should work automatically?

**Comment by JNeiger** [comment]
For right now, it'll be lower priority. I want a way to do a specific robot selection if it comes out cleaning in the future though.

**Comment by oswinso** [comment]
One thing I am curious about is whether "formations" based positioning or "zone" based positioning would be more effective. It seems that ZJU uses a zone based system slightly different from the proposed overhaul.

**Comment by kylestach** [comment]
This supports that as a potential future enhancement, by changing the implementation of the position class.

**Comment by JNeiger** [comment]
They aren't going to be constrained to a single point, but more general zones within that area that keeps the general position. It's hard to explain but it'd be a more formal version of what they do. I'm hoping they would be trying to get more open for passes and that kind of thing

**Comment by kylestach** [comment]
So, it looks like there's a bunch of logic to update the center of the formation, which as far as I can tell is unused (correct me if I'm wrong).

How exactly is this information used? I assume it should be used to dynamically shift the formation, right?

**Comment by JNeiger** [comment]
It's going to be reenabled once I figure the ball.x/y problem. It'll shift the formation around to stay within field boundaries as well as do something smarter than averaging the ball position like the prototype

**Comment by kylestach** [comment]
@JNeiger any update on this?

**Comment by JNeiger** [comment]
I fixed the ball pos thing, so I just need to fix the bug with formation center, then its good to merge. I'll probably leave it as is functionality wise. I need to mess with role requirements to get the "takeover" working.

**Comment by JNeiger** [comment]
Gonna say this is good enough break right now. Right now this just does formation creation. I think I need to redo how some of the low level role assignment works to really get nonbreaking behavior on stuff. I will probably go back eventually and clean up the long names and simplify stuff, but it's close enough to show what's happening right now.

**Review by kylestach — APPROVED** [review]
Looks good! I'm really excited about this.

**Comment by Jason27chan** [comment]
It looks good overall! I'd just like to understand better how this'll work with Chris' situation analysis

**Comment by JNeiger** [comment]
It doesn't directly interact with the situation stuff, but more so help the overall goal of creating more plays. Providing default locations for robots allow you to only use the ones you want to quickly improve the speed of play creation. Additionally, this allows better transitions between plays which is really important as we start using more than one with the situations.

**Review by Jason27chan — APPROVED** [review]

**Comment by kylestach** [comment]
@JNeiger is this mergeable as soon as mypy passes?

**Review by tjones320 — APPROVED** [review]
I still want to see how we are handling preemption, but I think this is a solid step forward. Super cool!

**Comment by JNeiger** [comment]
Oh whoops, I forgot I was crashing mypy and needed to fix that. I'll get on it.

**Comment by JNeiger** [comment]
Oof, this is annoying. I want to statically type a class function that returns a list of objects of that class. This isn't allowed in the current version so I have to use the `from __future__ import annotations` (See PEP 563). This breaks any type of python style or linter because `__future__` doesn't exist in their mind.

mypy and pylint have oneliners that I can use to disable the errors, but I think `test-python` doesn't use `python 3.7` like the others. It uses `python 3.6` so `__future__` actually doesn't exist and rightfully causes an error.

**Comment by JNeiger** [comment]
`test-python` is going to break, but I don't think that's me. The version of python on ci is 3.6 when we need 3.7. @kylestach is there somewhere where I can bump that version up?

**Comment by kylestach** [comment]
~Why do you need 3.7?~ (Edit: forgot to read above comment.) I'd rather not version bump considering Ubuntu 18.04 still comes with 3.6 default and I don't want to mess up the versioning on everyone's systems. I don't think it would be unreasonable to just leave that one method without type hinting, right?

**Comment by JNeiger** [comment]
It was fighting me earlier when I did it without, but I'll try again. There was probably a partial type hint somewhere.

**Comment by JNeiger** [comment]
asdf;lkjaweef;oiij Finally got it. Had to ignore the initial variable declaration type or it'd complain

**Pull request merged**
