### PR TITLE
Refactored InterpolatedPath to use MotionInstant and made Path.evaluate() return an optional instant

### PR DESCRIPTION
**Pull request by justbuchanan**
* renamed PathPlanner -> SingleRobotPathPlanner
* InterpolatedPath now has a vector of MotionInstant objects rather than separate vectors of position and velocity
* Path.evaluate() returns a boost::optional<MotionInstant> rather than having an output variable
* Removed unused methods: InterpolatedPath.{getPoint(), startFrom()}

### CODE REVIEW

**Comment by justbuchanan** [comment]
@ashaw596, I noticed that `InterpolatedPath`'s `getPoint()` and `startFrom()` methods aren't being used anywhere.  Can we get rid of them or do you think they'll have a use later?

**Comment by ashaw596** [comment]
Maybe? They've been in the class forever. That entire class is a bit messy since it is a point path class modified to work with velocities. Most of it is their just so it will work with RRT planner.

**Comment by ashaw596** [comment]
Yeah, I don't think those 2 are going to be used ever.

**Comment by ashaw596** [comment]
PathTest wasn't refactored btw.

**Comment by ashaw596** [comment]
Nice refactor btw.

**Comment by justbuchanan** [comment]
Cool, thanks.  I removed those two methods and fixed up the tests, so let me know if you see any issues.

**Comment by ashaw596** [comment]
looks good. I think there's still something not compiling in the tests though.

**Pull request merged**
