### PR TITLE
DS2411 ID Chip Driver

### PR DESCRIPTION
**Pull request by ra4king**
#187

### CODE REVIEW

**Comment by ra4king** [comment]
#187

**Comment by justbuchanan** [comment]
Nice work!  A few suggestions for improvements before we merge this:
* put a little more description in the header file for what this thing actually is.  You and I know, but someone that stumbles upon ds2411.hpp has no idea what it's actually for.
* have ds2411_read_id take in a PinName instead of a DigitalInOut - it's sort of an implementation detail that DigitalInOut is used, the user of the function should only have to specify what pin it's connected to.
* Move the debug printing stuff out of main.cpp and into the ds2411_read_id() function and have a bool parameter that defaults to false for whether or not it should be printed when the function is called.
* remove the blinking led stuff from main.cpp

Other than those things, it looks really good!

**Comment by ra4king** [comment]
Got the first three done.

For the blinking LED, I kept that in as initConsoleRoutine clears the screen. Can I have the LED blink a certain amount of times then continue to the console?

**Comment by justbuchanan** [comment]
Awesome!  The main() function is going to eventually be the actual program for running everything for the robot, so It's probably best to leave the LED thing out since that won't be on the final control board.

I think a good way to be able to test the ID stuff without cluttering main() would be to have `cmd_info()` (in commands.cpp) print the id stuff out after the git version info.  You can add a new pin declaration for the id chip to `robot.hpp` so `cmd_info()` knows which pin it's on.

**Comment by ra4king** [comment]
Ok I'll push what I have now and make those changes later, AFK for a bit.

**Comment by ra4king** [comment]
Hmm I don't know where to put the declaration of the DS2411_ID variable. It shouldn't be in `robot.hpp`, but it doesn't fit in any other C file. What do you suggest?

**Comment by justbuchanan** [comment]
I wouldn't make a global variable for the ID just yet.  We might eventually, but leave it out for now.  Just put a pin declaration in robot.hpp for where the chip is connected, then have the `cmd_info()` function re-read from id chip every time it's called.

**Comment by ra4king** [comment]
Oh so you did want me to re-read from the chip every time. Not the most efficient but it works for now.

**Comment by ra4king** [comment]
Done. The debug info prints out when 'info' is typed as a command in the console, right after the Git info.

**Comment by justbuchanan** [comment]
Awesome, I like it!  Only one thing left and I'll merge it.  Right now all the other pin mappings are #defined in robot.hpp under the comment "PIN DECLARATIONS", so it'd be best to put the ds2411 pin declaration up there too.  I do agree that doing `extern const PinName` for those is a little better than macros, but we should be consistent and do the pin declarations all the same.  If you want to do all the pins that way and put the actual definitions in a `robot.cpp` file, that'd be fine too.

**Comment by justbuchanan** [comment]
Actually I think the #define might be slightly better (even if less c++ "correct") b/c you can just look at the header and know exactly what the pins are actually mapped to instead of having to go back to the .cpp file.

**Comment by ra4king** [comment]
Oh! I never noticed those, the file was so long I just scrolled all the way to the bottom haha. I made it a #define.

**Comment by justbuchanan** [comment]
:+1:

**Pull request merged**
