### PR TITLE
changed all <math.h> to <cmath>

### PR DESCRIPTION
**Pull request by yousifd**

### CODE REVIEW

**Comment by jgkamat** [comment]
Everything looks good to me, :+1: 
We're going to wait for @justbuchanan to look at this before merging though.

Congrats on your first contribution! :smiley:

**Comment by yousifd** [comment]
Thank you. Hope to do more, and looking at your project it seems cool.

**Comment by ashaw596** [comment]
Looks good to me too. I think you got them all. There's 2 left in firmware, but that can be left alone for now. Awesome!!!!!!

**Comment by yousifd** [comment]
@ashaw596 could you point them out? The only one I see is a C file and I think that it does not support the c++ libraries.

**Comment by jgkamat** [comment]
One of them is a comment in `robot/cpu/commands.c`, and one of them is commented out in `robot2015/cpu/robot.hpp`, so I think this is good!

**Comment by ashaw596** [comment]
Yep just those 2. Its not part of soccer anyways. The c file is also probably going to be deprecated sometime this year too.

**Comment by yousifd** [comment]
Oh, that is good to hear. I skipped the commented one in <code>robot2015/cpu/robot.hpp</code> since it would be removed later or revised by anyone who updates it later.

**Comment by justbuchanan** [comment]
Looks great to me!  Thanks for doing this, I'll merge it in a sec.

**Pull request merged**
