### PR TITLE
Stp cleanup

### PR DESCRIPTION
**Pull request by kfu02**
## Description
Removes some unused files to make [revamping role assignment](https://docs.google.com/document/d/142vupUUbpNRlskvNIYaSFyo0AoFJjoLedKMVEbY0-A0/edit?usp=sharing) easier.

## Associated Issue
n/a

## Design Documents
n/a

## Steps to test
Build and run sim. Should work the same still.

Expected result: ^

### CODE REVIEW

**Review by Yudai-8-om — APPROVED** [review]
Worked

**Review by echen0918 — COMMENTED** [review]
move_tactic, pass_seek, and striker_tactic have some mypy errors to be fixed; all the deleted files and other changes seem fine.

**Review by echen0918 — CHANGES_REQUESTED** [review]
move_tactic, pass_seek, striker_tactic have mypy errors to be fixed

**Comment by kfu02** [comment]
To be honest, those three files will be completely reworked in #1811 anyways, so I'm not going to fix the mypy errors for now. In #1811 if you spot these errors please let me know, however.

**Review by echen0918 — APPROVED** [review]

**Pull request merged**
