### PR TITLE
Added option flags to ubuntu-setup

### PR DESCRIPTION
**Pull request by jgkamat**
I added a bunch of flags that should help with automation (especially in docker). In addition, I added the svg binaries. 

I'm still testing this on a clean ubuntu install, but it seems to work fin if you have previously run the script

Currently, on ubuntu installs, it installs only the cmake repo by default, and the firmware if provided the --firmware flag. On debian, no repos are added by default, but that can be forced with the -c flag. See -h for more details.

Partially solves #191

### CODE REVIEW

**Comment by jgkamat** [comment]
That last commit fixed a few things, but it still seems to be failing...

**Comment by jgkamat** [comment]
It seems like the gcc version isn't getting upgraded properly...

**Comment by jgkamat** [comment]
Yay! Looks like all that was missing was a dependency!
I'll be able to test the ubuntu-setup script as soon as it's merged, but it seems to work fine right now

**Comment by jgkamat** [comment]
Yay! Looks like all that was missing was a dependency!
I'll be able to test the ubuntu-setup script as soon as it's merged, but it seems to work fine right now

**Comment by justbuchanan** [comment]
Looks good!  I'd be inclined to have the firmware option default to true though since a lot of people will be using it and are used to running `ubuntu-setup` without arguments.

**Comment by jgkamat** [comment]
Hold on, dont merge this yet, it seems like there is a debian reference in os-release

**Comment by jgkamat** [comment]
If you know a better way of determining if this is running on a Ubuntu/Debian machine, let me know, but this seems to work fine so far

**Comment by jgkamat** [comment]
[looks like this script is looking good with --firmware and -y](https://registry.hub.docker.com/u/jgkamat/robocup-baseimage/build_id/25023/code/bpx9jjgsnemmpqhyt6qpxa/). If anyone has any issues with the flags, let me know and i'll fix them.

**Pull request merged**
