### PR TITLE
Replaced radian-degree conversion constants with macro function. Closes #413

### LINKED ISSUE #413: Replace the constants to convert between degree to radians with an inline function or macro
replace common/geometry2d/util.h constant with macro or inline function

### PR DESCRIPTION
**Pull request by ItsDaSpecialK**
Replaced the Radian to Degree and Degree to Radian constants with two macro functions. Closes Issue #413

### CODE REVIEW

**Comment by jgkamat** [comment]
Dont worry about the coverage failure, this LGTM.

**Comment by jgkamat** [comment]
We need to solve the master branch differences on CI, @justbuchanan 

This PR is still fine.

**Comment by ashaw596** [comment]
Just checkstyle. run make pretty.

**Comment by justbuchanan** [comment]
Cool, looks good! :+1:

**Pull request merged**
