### PR TITLE
Defense Chooses Roles

### PR DESCRIPTION
**Pull request by sid-parikh**
## Description
Describe your pull request.

## Associated / Resolved Issue
Resolves # or [ClickUp card](link-to-clickup-card)

## Design Documents
[Link](link-to-design-doc)

### Test Case 1
1. Step 1
2. Step 2
3. Step 3

**Expected result:**???

## Key Files to Review
Group 1
 * File 1
 * File 2

Group 2
 * File 3
 * File 4

## Review Checklist

- [ ] **Docstrings**: All methods and classes should have the file appropriate docstrings which follow the guidelines in the ["Contributing" page](https://rj-rc-software.readthedocs.io/en/latest/contributing.html) of our docs.
- [ ] **Remove extra print statements**: Any print statements used for debugging should be removed
- [ ] **Tag reviewers**: Tag some people for review and ping them on Slack

## (Optional) Sub-issues (for drafts)
_Note: if you find yourself breaking this PR into many smaller features, it may make sense to break up the PR into logical units based on these features._
- [ ] Step 1
- [ ] Step 2

### CODE REVIEW

**Comment by sid-parikh** [comment]
@kfu02 this is my solution for picking defense roles quickly for testing — I had to force the goalie ID into action client. is that fine?

eventually this should be replaced with communication between defense robots, which we'll work on but this way testing can start

we could alternatively split defense into two positions and let coach assign them.

**Comment by kfu02** [comment]
> @kfu02 this is my solution for picking defense roles quickly for testing — I had to force the goalie ID into action client. is that fine?
> 
> eventually this should be replaced with communication between defense robots, which we'll work on but this way testing can start
> 
> we could alternatively split defense into two positions and let coach assign them.

actually, I wouldn't mind if the goalie id was in the Position superclass. I think it's fine that the positions know what the Goalie is at all times. the only issue I have with your current implementation is that you have it in the constructor, so if the Goalie ID changes at runtime that won't be reflected in the Defense class

**Comment by kfu02** [comment]
take a look at how world_state is updated by AgentAC and sent to the Position superclass. you can do something similar for goalie ID

https://github.com/RoboJackets/robocup-software/blob/29bec7bec27dfd25e8c7422a46aad9b6a00c86c0/soccer/src/soccer/strategy/agent/agent_action_client.cpp#L67

https://github.com/RoboJackets/robocup-software/blob/29bec7bec27dfd25e8c7422a46aad9b6a00c86c0/soccer/src/soccer/strategy/agent/position/position.cpp#L44

**Comment by sid-parikh** [comment]
@N8BWert is this PR still relevant?

**Comment by p-nayak11** [comment]
Functionality in this PR was merged a while ago. Stale branch is now closed.

**Pull request closed without merging**
