### PR TITLE
Detectionball msg rosconverter

### PR DESCRIPTION
**Pull request by joshkirsh720**
## Description
Make SSL Ball to ros message conversion and rosconverter

## Associated Issue
Issue #1588 

##Design Documents
N/A

### Test Case 1
1.Run soccer

Expected result: No regression expected

### CODE REVIEW

**Comment by kylestach** [comment]
It looks like the CI issue we're seeing is because `rj_utils` currently doesn't have a dependency on the `rj_convert` library. You can fix this by adding a dependency in `rj_utils/CMakeLists.txt`:
```cmake
target_dependencies(rj_utils PUBLIC rj_convert)
```
You can just put this after the `ament_target_dependencies` declaration.

**Review by kfu02 — APPROVED** [review]
Looks good to me!

**Review by kasohrab — APPROVED** [review]
Looks good!

**Review by HussainGynai — APPROVED** [review]
LGTM

**Review by kylestach — APPROVED** [review]

**Pull request merged**
