### PR TITLE
Field dimensions update

### PR DESCRIPTION
**Pull request by amoghp214**
## Description
The FieldDimensions struct is expanded to contain useful calculated geometric values. These can be accessed by subscribing to the `config/field_dimensions` topic and then using `rj_convert` to convert the message type into the struct.

## Associated / Resolved Issue
https://app.clickup.com/t/3347qra

## Testing
no visible changes; for future (as seen in #2019)

## Key Files to Review
 * field_dimensions.hpp

## Review Checklist

- [x] **Docstrings**: All methods and classes should have the file appropriate docstrings which follow the guidelines in the ["Contributing" page](https://rj-rc-software.readthedocs.io/en/latest/contributing.html) of our docs.
- [x] **Remove extra print statements**: Any print statements used for debugging should be removed
- [ x **Tag reviewers**: Tag some people for review and ping them on Slack

### CODE REVIEW

**Review by kfu02 — DISMISSED** [review]
run `make pretty-lines` please

**Comment by kfu02** [comment]
hey @amoghp214, you have to resolve the merge conflicts with ros2 here before the checks can run, try `git submodule update –remote`

If that fails, simply cd to `external/robocup-fshare` and git pull master

**Comment by sid-parikh** [comment]
Simplified this PR down to all it is supposed to do — add some extra data to FieldDimensions for less math later on

**Review by p-nayak11 — CHANGES_REQUESTED** [review]
Fix all of the GitHub Action Warnings. Most of them are just adding [[nodiscard]] to some attributes.

**Comment by sid-parikh** [comment]
Not sure how I didn't notice this, but the new FieldDimensions makes vision crash immediately on startup. Not ready for merge

**Comment by sid-parikh** [comment]
first 7 commits modify `field_dimensions.hpp` (original PR) and the next 9 modify strategy files to match (PR #2019)

**Review by kfu02 — APPROVED** [review]
LGTM

**Pull request closed without merging**
