### PR TITLE
Casted the value returned by sizeof()

### LINKED ISSUE #868: Sizeof value should be cast to long unsigned int
In USBRadio.cpp line 237, the sizeof parameter should be cast to an int because fprintf requests an int

### PR DESCRIPTION
**Pull request by kevinatorchen**
Closes #868

### CODE REVIEW

**Comment by joshhting** [comment]
I made a change to #868 that you should look at @kevinatorchen

**Comment by kevinatorchen** [comment]
All right, I modified it.

**Comment by joshhting** [comment]
@jgkamat external/sdlcontrollerdb was modified in the new commit as well, should that portion be reverted?

**Comment by jgkamat** [comment]
I've just pushed a commit to resolve the submodule problems, you should be good to merge now!

**Comment by kevinatorchen** [comment]
Can we close this pull request and issue?

**Comment by jgkamat** [comment]
Yah, I'll do that now, my bad.

**Pull request merged**
