### PR TITLE
fixed udev rules for mbed

### PR DESCRIPTION
**Pull request by justbuchanan**
* if multiple mbeds are plugged in, they each get their own name at /dev/mbed[0-9]+
* {arch, ubuntu}-setup scripts now reload udev rules after installing

### CODE REVIEW

**Comment by justbuchanan** [comment]
If two mbeds are plugged in, they'll now show up as `/dev/mbed0` and `/dev/mbed1`.  Previously only one of them would show up as `/dev/mbed`.

**Comment by jgkamat** [comment]
the udevadm control -R is failing with exit code 2, which is why the build is failing. I don't know why though...

**Comment by justbuchanan** [comment]
Yeah I'm not sure why either :/.  It works fine on my ubuntu vm, so I wonder if it's something docker-related.

**Comment by jgkamat** [comment]
Yah, it looks fine, I'll look into this..

**Comment by jgkamat** [comment]
Its complaining that it cannot find 
`/run/udev/control` 
in the docker containers, which is true.

Not sure about what to do about it though...
We could try to symlink the hosts udev control to inside the container if we want.

**Comment by justbuchanan** [comment]
Hmm, that's a possibility.  Not sure how socket communication like that works through container boundaries though.

I could just remove the command to reload udev rules, but it would be sorta nice to have :/

**Comment by jgkamat** [comment]
Worst case scenario, we could || true it, but I don't want to do that too much...

**Comment by justbuchanan** [comment]
Yeah I think `|| true` will work here.  In general we should avoid it, but it's ok for rule reloading to fail here.

**Pull request merged**
