### PR TITLE
Switch over to DoCIF

### LINKED ISSUE #461: Add .gitmodules file to setup script checksum for circleci
Looks like changes to submodules are breaking some ci builds because the base image isn't being rebuilt.  This is the case for the [ninja branch](https://circleci.com/gh/RoboJackets/robocup-software/576) at the moment.

### PR DESCRIPTION
**Pull request by jgkamat**
Now our Docker based CI is controlled from a singular config file, and is mostly portable to other platforms. I'm not 100% sure deployment works though, but other than that I've tested the things we personally use and they look good!

Closes #461
Lets not merge this until after the meeting earliest...

### CODE REVIEW

**Comment by justbuchanan** [comment]
:+1:

**Comment by justbuchanan** [comment]
It seems to be all working, so go ahead whenever you're ready.

**Comment by jgkamat** [comment]
I'll merge this at about 3:30, and if there are any deployment issues I'll fix them as they come up.

**Comment by justbuchanan** [comment]
I just fixed the submodules for this branch, but it's still having a permissions issue.

**Comment by jgkamat** [comment]
I think I've fixed that permissions issue, can I go ahead an merge this (I'll follow up if there are issues)

**Comment by justbuchanan** [comment]
Sounds good, go for it!

**Comment by jgkamat** [comment]
Looks like it worked :tada: 
Let me know if you see any problems and I'll get right on it

**Comment by justbuchanan** [comment]
Awesome, nice work!  Everything's looking good.

**Pull request merged**
