### PR TITLE
Adding delay tasks to ps command

### PR DESCRIPTION
**Pull request by jjones646**

### CODE REVIEW

**Comment by jjones646** [comment]
@justbuchanan

**Comment by justbuchanan** [comment]
related to #583

**Comment by JNeiger** [comment]
I'm only seeing 2 threads (ID: 1 and 3) when I run it. Shouldn't there be 3? The `Main`, `Controller`, and `Console` thread?

**Comment by justbuchanan** [comment]
The `CommModule` has 2 threads too, I think there's 6 threads total.

**Pull request merged**
