### PR TITLE
referee_module_enums (replaces RefereeModuleEnums) Issue #1590

### PR DESCRIPTION
**Pull request by RyanBard7**
## Description
Namespace changed to referee_module_enums from RefereeModuleEnums

## Associated Issue
Issue #1590 

## Design Documents
[Link](link-to-design-doc)

### CODE REVIEW

**Review by HussainGynai — CHANGES_REQUESTED** [review]
Looks like your making a PR into staging, which is why it says you have 1,030 files that need changing, you should make the PR into the ros2 branch

**Comment by kylestach** [comment]
Heads up, it looks like you made the base branch `staging` instead of `ros2`. I've fixed that for you.

**Comment by kylestach** [comment]
Oops, Hussain beat me to it. Also, it looks like you didn't commit your new code yet so be sure to do that before pushing.

**Review by kylestach — APPROVED** [review]

**Comment by kylestach** [comment]
This is ready for review @gauravgarre @joshkirsh720

**Review by joshkirsh720 — APPROVED** [review]
Looks good

**Review by HussainGynai — APPROVED** [review]

**Pull request merged**
