### PR TITLE
Added a new page for 2015 firmware documentation

### PR DESCRIPTION
**Pull request by jgkamat**
Started the documentation for the 2015 firmware, and also included debugging information for the arm compiler on ubuntu.

### CODE REVIEW

**Comment by justbuchanan** [comment]
Awesome, thanks for getting this started!

A couple notes after reading over it:
* In the first section, you mention the DIP switches for changing settings - our old boards had these, but I don't know that our new ones will.  @jjones646, can you comment on this?
* The "Debugging" section talks about how to install the ARM compiler, so it might be better named Compiler Toolchain or Compiling Firmware.

**Comment by jjones646** [comment]
The dip switches will still be there, but their functions will be different. What they will actually control will come about as the firmware progresses.

**Comment by jgkamat** [comment]
I changed a few things, is there anything else that should be updated?

**Comment by justbuchanan** [comment]
Cool, looks good to me.  I'll go ahead and merge it.

**Pull request merged**
