### PR TITLE
<shrikar>/robocup sw tutorial

### PR DESCRIPTION
**Pull request by davibinboi**
Completes RC SW tutorials.

### CODE REVIEW

**Comment by davibinboi** [comment]
> Completes RC SW tutorials.

robocup 4 waller

**Comment by davibinboi** [comment]
team fruit changing

**Comment by davibinboi** [comment]
@sid-parikh 
Was confused with the ROS notation for classes, nodes, and motion commands.

**Comment by sid-parikh** [comment]
i'll review this before you close it

**Pull request closed without merging**
