### PR TITLE
created basic defend restart play that is just a goalie and 5 markers

### PR DESCRIPTION
**Pull request by HussainGynai**
## Description
Just 5 markers and a goalie.

### CODE REVIEW

**Comment by kylestach** [comment]
Maybe it would be good to have two or so robots dedicated to walling?

**Comment by HussainGynai** [comment]
> Maybe it would be good to have two or so robots dedicated to walling?

My thought as that they can't directly kick at goal right?

**Comment by kfu02** [comment]
should the is_done method be tied to the is_done of the markers?

**Comment by kfu02** [comment]
LGTM

**Pull request merged**
