### PR TITLE
Motor testing program

### PR DESCRIPTION
**Pull request by justbuchanan**
If we can refactor this into a test in the "hw-test" folder, it'd be a useful thing to have.

TODO:
- [ ] Test with hardware

### CODE REVIEW

**Comment by jjones646** [comment]
haven't tested on hardware, but it compiles so far.

**Comment by jjones646** [comment]
related to #633

**Comment by justbuchanan** [comment]
@jjones646 If we want to merge this as a stand-alone test program, the code to read the radio selector needs to go in motors-test.cpp file.  With it in ControllerTaskThread as it is now, it affects the main robot firmware.

**Comment by jgkamat** [comment]
@guyfleeman was this merged manually into master? iirc, we had a working motor test program at comp.

**Comment by jgkamat** [comment]
At some point, the motor test moved to RoboJackets/robocup-firmware (I think), so this isn't needed. If anyone can confirm this, please delete this branch too.

**Comment by petersonev** [comment]
A couple days ago I remade the motor test in firmware so this branch shouldn't be needed any more

**Comment by jgkamat** [comment]
Just in case, the branch will remain available (for as long as possible) here: https://gitlab.com/RoboJackets/robocup-software/tree/jon/motor-testing

**Pull request closed without merging**
