### PR TITLE
Kill background simulators when running make run-sim

### PR DESCRIPTION
**Pull request by jgkamat**
I got really sick of the headless simulator being reused when running `make run-sim`, so I added a line to the makefile to kill the headless simulator when run-sim starts. Should I add it to run after the execution instead?

The line should be ignored if it fails

Also, I'm not sure if macs have pkill installed (its not posix). If thats the case, then I can convert this to use standard ps and kill.

### CODE REVIEW

**Comment by justbuchanan** [comment]
Cool, I like it - simulators fighting each other is a pain in the butt haha.  I looked it up online and I think OSX does come with pkill.  I'd check, but my Mac is having issues right now.  @ashaw596 , can you check if this works on OSX?

I think at some point it would be nice to add a flag to the simulator so doing something like `simulator --timeout=5` would tell it to exit if it goes for five seconds without receiving any new "radio" packets.  That way we don't have to explicitly kill it, it would just gracefully exit after you close soccer.  We can do this sometime after comp though.

**Comment by jgkamat** [comment]
I switched it over to use ps and kill, because we might as well try to support as many systems as possible :smile: 

I had to escape my `$`s like this `$$` though, I'm assuming thats standard....

**Comment by justbuchanan** [comment]
Ok cool.  Well if the first one works on OSX (I think it will), I'd rather go with it since it's much simpler.  If we have to go with option two for compatibility then we can.

I'll go ahead and merge version one and if it breaks OSX, we'll pull version two.

**Comment by jgkamat** [comment]
:+1: sounds good to me!

**Comment by ashaw596** [comment]
I've used pkill on my comp before so it'll probs work. Might have installed
it myself tho. Don't think so so it's probs good.

**Comment by justbuchanan** [comment]
I looked at this again, and I think if we actually did `killall simulator` it might be slightly better because we don't have to include the flags that we passed to it originally.  And I've used killall on OSX plenty of times.

**Comment by jgkamat** [comment]
I originally was going for only stopping headless simulators, but if we're fine with stopping all simulators, then that probably works better!

**Comment by justbuchanan** [comment]
Yeah that's a fair point, let's leave it as is then.  I'll add an issue for adding a timeout option to the simulator, but we can do that sometime after comp.

**Pull request closed without merging**
