### PR TITLE
Fix Spelling Mistakes

### PR DESCRIPTION
**Pull request by akhilveeraghanta**
## Description

While snooping through your code, I noticed a spelling mistake, and took this opportunity to run `codespell -w` because its extremely therapeutic

My favorite thing about @kylestach is the way he spells

## Associated Issue

Spelling
## Design Documents

[https://www.wikihow.com/Spell-a-Difficult-Word](https://www.wikihow.com/Spell-a-Difficult-Word)
[https://www.wikihow.com/Learn-to-Remember-Spellings-of-Words](https://www.wikihow.com/Learn-to-Remember-Spellings-of-Words)
### Test Case 1
1. Read the spelling
2. Make sure its more correct than what it was before

Expected result: Word can be understood

## (Optional) Sub-issues (for drafts)
_Note: if you find yourself breaking this PR into many smaller features, it may make sense to break up the PR into logical units based on these features._

### CODE REVIEW

**Review by MathewMacDougall — APPROVED** [review]
What a great idea! We'll teach those Americans how to spell :canada: 

LGTM :+1:

**Comment by jonathanlew** [comment]
nit:
> My ~favorite~ thing about @kylestach is the way he spells

My favo**u**rite thing about @kylestach is the way he spells

**Review by garethellis0 — APPROVED** [review]
Truly the most significant contribution to this repository in living memory. 

Pretty sure this means we can take credit for any and all RoboJackets success.

@kylestach @oswinso

:trollface: :zap: :zap: :zap: :canada:

**Comment by MathewMacDougall** [comment]
The only reason this didn't affect more lines is because there's no comments for it to format :fire: :eyes: :trollface:

**Review by JNeiger — APPROVED** [review]
lmaoo

**Review by jonathanlew — APPROVED** [review]

**Comment by oswinso** [comment]
No wonder we can't recieve the ball - we can't even spell it properly

**Review by oswinso — APPROVED** [review]
We need to add this to continous integration so that spelling mistakes from candiate branches dissapears and we dont recieve any more spelling mistake PRs.

**Comment by kylestach** [comment]
@oswinso
> continous

> candidate

> dissapears

> dont

...

Edit: I feel like there were just enough mistakes that it wasn't accidental, but not enough that it was on purpose...I genuinely can't tell if I'm being wooshed. Sigh.

**Review by jgkamat — APPROVED** [review]
This is the greatest change in the history of this project

**Comment by oswinso** [comment]
> @oswinso
> 
> > continous
> 
> > candidate
> 
> > dissapears
> 
> > dont
> 
> ...
> 
> Edit: I feel like there were just enough mistakes that it wasn't accidental, but not enough that it was on purpose...I genuinely can't tell if I'm being wooshed. Sigh.

smh didn't even find recieve

**Comment by oswinso** [comment]
Also, the tool misidentified a string as a comment and so added a `'` into a python string that uses `'`, which is making CI fail....

**Comment by kylestach** [comment]
The clang-tidy error is on soccer/planning/planners/RRTPlanner.hpp:104, it should be `const`. You can skip it if you want to, though, it's just detecting the line as changed.

If you could run the formatter with `make pretty-lines` to fix style CI, that would be great (or I can do it).

**Comment by akhilveeraghanta** [comment]
image
ran all these, no diffs from them, can't see the output of style and clang-tidy so not sure what happened

**Pull request merged**
