### PR TITLE
Offense revamp

### PR DESCRIPTION
**Pull request by rishiso**
## Description
Merging seek behavior into offense.

## Associated / Resolved Issue
Resolves # or [ClickUp card](link-to-clickup-card)

## Design Documents
[Link](link-to-design-doc)

### Test Case 1
1. Step 1
2. Step 2
3. Step 3

**Expected result:**???

## Key Files to Review
Group 1
 * File 1
 * File 2

Group 2
 * File 3
 * File 4

## Review Checklist

- [ ] **Docstrings**: All methods and classes should have the file appropriate docstrings which follow the guidelines in the ["Contributing" page](https://rj-rc-software.readthedocs.io/en/latest/contributing.html) of our docs.
- [ ] **Remove extra print statements**: Any print statements used for debugging should be removed
- [ ] **Tag reviewers**: Tag some people for review and ping them on Slack

## (Optional) Sub-issues (for drafts)
_Note: if you find yourself breaking this PR into many smaller features, it may make sense to break up the PR into logical units based on these features._
- [ ] Step 1
- [ ] Step 2

### CODE REVIEW

**Review by kfu02 — CHANGES_REQUESTED** [review]
hey, please merge ros2 into this branch, there are a lot of files changed that I assume you didn't change personally

EDIT: also ensure before merging that your machine's ros2 is up to date. see our documentation

**Review by kfu02 — CHANGES_REQUESTED** [review]
thanks @Ninjatest321, seems like this version of the code does not compile, though?

**Comment by rishiso** [comment]
Sorry, I have been busy with midterms this week. I will get on this ASAP.

**Comment by rishiso** [comment]
I am not sure what you guys did, but all of the changes I made (including the seeker.cpp and seeker.hpp files) are no longer in this branch.

EDIT: Nevermind, I see what happened. The reason it is not compiling is because that is the first version of the receive role. I fixed it in a later version of the branch. However, I am still not sure how to recover all of the changes for the seek behavior.

**Comment by kfu02** [comment]
> I am not sure what you guys did, but all of the changes I made (including the seeker.cpp and seeker.hpp files) are no longer in this branch.
> 
> EDIT: Nevermind, I see what happened. The reason it is not compiling is because that is the first version of the receive role. I fixed it in a later version of the branch. However, I am still not sure how to recover all of the changes for the seek behavior.

Ah okay, the changes should still exist locally on your machine, don't worry. We can fix it next week

**Pull request closed without merging**
