### PR TITLE
moved Time and timestamp() into RJ namespace.  closes #472

### LINKED ISSUE #472: Fix issue with X11's definition of Time colliding with ours
Maybe by putting our stuff inside an `rj` namespace?

cc @hmistry1

### PR DESCRIPTION
**Pull request by justbuchanan**
@hmistry1, this should fix the issue you were having yesterday.  Can you check out this branch and see if you can build and run soccer on your computer?  Reply to this thread if you have any questions about how to do this.  The process should be:

~~~{.sh}
git fetch
git checkout origin/justin/time-fix
make clean
make run-sim
~~~

closes #472

### CODE REVIEW

**Comment by hmistry1** [comment]
Sorry for the delayed response. I tried the commands, but it says that
origin/justin/time-fix does not match any files known to git.

On Sun, Oct 25, 2015 at 1:34 PM, Justin Buchanan <notifications@github.com>
wrote:

> Merged #473 <https://github.com/RoboJackets/robocup-software/pull/473>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RoboJackets/robocup-software/pull/473#event-444909545>
> .
>



-- 
Hariank Mistry

**Comment by jgkamat** [comment]
Try out the latest master:
```
git fetch
git checkout origin/master
make clean
make run-sim
```
This was merged, so that branch dosent exist anymore (but the fix should be on master).

**Comment by hmistry1** [comment]
I ran the commands, but it is giving me the same error.

On Mon, Oct 26, 2015 at 10:16 PM, Jay Kamat <notifications@github.com>
wrote:

> Try out the latest master:
>
> git fetch
> git checkout origin/master
> make clean
> make run-sim
>
> This was merged, so that branch dosent exist anymore (but the fix should
> be on master).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RoboJackets/robocup-software/pull/473#issuecomment-151344772>
> .
>



-- 
Hariank Mistry

**Comment by justbuchanan** [comment]
Hmm, that's odd.  Can you post the output of running `git rev-parse HEAD`?  I just want to make sure you're up to date with the latest.  Are you sure you recently pulled the latest from master?

**Comment by hmistry1** [comment]
It says 31758fc0707b6091569af254c2f20c0d9318e8a4

On Tue, Oct 27, 2015 at 3:39 PM, Justin Buchanan <notifications@github.com>
wrote:

> Hmm, that's odd. Can you post the output of running git rev-parse HEAD? I
> just want to make sure you're up to date with the latest. Are you sure you
> recently pulled the latest from master?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RoboJackets/robocup-software/pull/473#issuecomment-151620452>
> .
>



-- 
Hariank Mistry

**Comment by jgkamat** [comment]
Er, we should have done a 
```
git fetch robojackets
git checkout robojackets/master
```
then the rest of the commands.

**Comment by jgkamat** [comment]
This is good (works now).

**Pull request merged**
