### PR TITLE
Add short Git commit hash to main soccer window title

### LINKED ISSUE #795: Put the git commit hash in the window title
Or somewhere where it can easily be found

### PR DESCRIPTION
**Pull request by petschekr**
Fixes #795

### CODE REVIEW

**Comment by jgkamat** [comment]
Hi @petschekr! Thanks for your first PR! While this does get the job done just fine, this method is a little bit rough around the edges, and presents some problems. For example, when `soccer/version.hpp` is generated, committing that file would cause the sha to change, requiring us to commit again (indefinitely). While we could `.gitignore` that file, we already have a system for getting the git version in the program, baked into our CMake!

I made a [similar PR](https://github.com/RoboJackets/robocup-software/pull/221) about a year ago to add the same thing to the firmware. We've already set up the build system to have the `git_version.hpp` file included when building soccer, so all you need to do is:

1. Add `#include <git_version.hpp>` to the MainWindow file.
2. Use the variable `git_version_hash` brought in from there

This is the long commit hash though, so you may want to shorten it using C++, but I'll leave that up to you :smile:.

You can modify this PR by pushing further changes to your branch. I'll be happy to merge once you switch to using the above method (since it's what we use [elsewhere in soccer](https://github.com/RoboJackets/robocup-software/blob/master/soccer/Processor.cpp#L265)).

Thanks again, and I'll be on gitter and here if you run into any issues. Thanks again!

**Comment by petschekr** [comment]
@jgkamat Thanks for the help! Didn't realize that the Git status information was already there. I made a small change to `CMakeLists.txt` in `common/` to add a `git_version_short_hash` variable to the Git version header file. Since common/ is really a submodule pointing to [robocup-common](https://github.com/RoboJackets/robocup-common), do I have to fork and submit a pull request to that repository as well with the one commit I made that 536e5d9 is dependent on?

**Comment by jgkamat** [comment]
Yup, exactly! Go ahead and fork RoboJackets/robocup-common, push your common changes to there (you can use `git push <your fork url> master` inside the common folder), and submit a PR to common. 

Submodules are a bit tricky, so I would be happy to help you out with that if you got stuck.

The changes on this PR look good to me at a first glance though, nice job!

**Comment by petschekr** [comment]
Alright, I submitted a [pull request to robocup-common](https://github.com/RoboJackets/robocup-common/pull/3) with the changes necessary to make this compile properly.

**Comment by jgkamat** [comment]
Nice job! We're almost done, I think your changes are good, and everything seems to work for me!

The last step is to run the auto formatter (we have an automated code linter that detects and fixes style violations). To fix the style error could you run:
`git apply <(curl -L https://circle-artifacts.com/gh/RoboJackets/robocup-software/2943/artifacts/0/tmp/circle-artifacts.0eV7Tp1/clean.patch)`
and make/push a commit with the changes applied?

Just for future reference, that link can be found in the details page of the style check if it fails.

Once you've done that final step, I'll go ahead and merge it! :+1:

**Comment by jgkamat** [comment]
LGTM, if status passes, I'll go ahead and merge.

Congrats on your first PR! Let us know if you want to start working on tackling some more advanced issues, and we'll give you some pointers and help you out! :smile:

**Comment by petschekr** [comment]
Awesome! Thanks for the help on getting this merged!

**Pull request merged**
