### PR TITLE
Fixes the artifact deployment on a failure

### LINKED ISSUE #726: Build not publishing artifacts when build fails.
I suspect this is because we fail during the dependency step, rather than the testing step (to take advantage of circleci caching). If they can't fix it for some reason, we'll carry the failure into the testing stage, and everything should work.

This is more of an announcement for anyone trying to get their build artifacts, than a true issue here.

### PR DESCRIPTION
**Pull request by jgkamat**
Closes #726 

This fixes that artifact deployment bug we saw earlier @justbuchanan

### CODE REVIEW

**Comment by justbuchanan** [comment]
Nice!  I was missing having our logs :)

LGTM :+1:

**Comment by jgkamat** [comment]
I'm going to see if that last commit passes, if it does, I'll go ahead and merge.

**Comment by jgkamat** [comment]
Also just wanted to let you know this is at the bottom of the build step now =)

screen shot 2016-06-22 at 9 33 34 pm

**Comment by justbuchanan** [comment]
That's pretty slick, I like it!

**Pull request merged**
