### PR TITLE
Attempt to allow PR's from seperate forks

### PR DESCRIPTION
**Pull request by jgkamat**
Github apparently is really smart and invalidates api tokens pushed to GH, so I 'worked around that'.

Other than that, this looks good. See #401 for it in action.

### CODE REVIEW

**Comment by justbuchanan** [comment]
Looks good to me.  How GITHUB_HAS_GREAT_SECURITY token work?

**Comment by jgkamat** [comment]
Github actually checks to see if your token is pushed to github, and invalidates it if it sees it. So I just split it in two (and then github can't invalidate the token)

**Comment by justbuchanan** [comment]
Ahh ok, makes sense.  Want to put a comment in the circle file describing that?

**Comment by justbuchanan** [comment]
How do they invalidate it if it's just entered into the circle environment variables, but never committed/pushed to GitHub?

**Comment by jgkamat** [comment]
circle.yml is on github (thats the way to add environmental variables that arent blocked on seperate forks). Normal env. vars are blocked, but things in circle.yml are public and added in every scenario.

**Comment by justbuchanan** [comment]
Makes sense, I forgot circle blocks environment variables on separate forks.

**Comment by jgkamat** [comment]
I added back the pushing to the master tag as part of this PR, but this time, in the deployment step, so it doesn't slow down the results of the builds.

**Comment by justbuchanan** [comment]
Nice, I like it!  Feel free to merge this if it's ready.

**Comment by jgkamat** [comment]
This made master red because [docker hub is down right now](https://status.docker.com/). If this continues we might have to force this to always return true. But this is the first time I've seen this happen...
I'll rebuild this once it goes back up

**Pull request merged**
