### PR TITLE
Added a few geometry tests

### PR DESCRIPTION
**Pull request by JNeiger**
## Description
Added some tests to geometry

### Test Case 1
1. Run `make test-cpp`

Expected result: Passes

### CODE REVIEW

**Comment by JNeiger** [comment]
My install is completely broken since I'm still on 19.04 I think, so someone else is going to have to do the clang-tidy and make pretty-lines unless I can apply a patch from circleci

**Comment by oswinso** [comment]
I can do it for you

**Comment by JNeiger** [comment]
@oswinso Just updated a line so you may have to pull again if you're doing it rn

**Comment by oswinso** [comment]
alright done

**Comment by oswinso** [comment]
I cherry picked 8e4a754e1ac0f3e9e0fd39ebc1e02f5dc889b446 to fix the `clang-tidy` issues with `gtest`

**Comment by JNeiger** [comment]
Thanks!

**Review by oswinso — APPROVED** [review]
lgtm

**Review by kylestach — APPROVED** [review]
LGTM

**Pull request merged**
