### PR TITLE
Constants

### PR DESCRIPTION
**Pull request by dwu359**
## Description
Added strategy constants

## Associated / Resolved Issue
Resolves [log all of strategy topics in rj_constants](https://app.clickup.com/t/8677kn5xw)

**Expected result:**
Don't crash

## Key Files to Review
Group 1
 * rj_constants/topic_names.hpp
 * coach_node.cpp
 * agent_action_client.cpp

## Review Checklist

- [ ] **Docstrings**: All methods and classes should have the file appropriate docstrings which follow the guidelines in the ["Contributing" page](https://rj-rc-software.readthedocs.io/en/latest/contributing.html) of our docs.
- [ ] **Remove extra print statements**: Any print statements used for debugging should be removed
- [ ] **Tag reviewers**: Tag some people for review and ping them on Slack

### CODE REVIEW

**Review by p-nayak11 — CHANGES_REQUESTED** [review]
Sorry for the design changes, but could you end all of the constant names to end with ~Topic instead of ~Pub. This will mean that all of the other instances of the constants will be changed in the other files. Good job on getting it done though!

**Review by kfu02 — CHANGES_REQUESTED** [review]
Overall looks good, can you merge in ros2 to this branch (so it has your auto-styling changes)?

**Review by kfu02 — CHANGES_REQUESTED** [review]
Looks good, you have a merge conflict with planner_node.cpp now (because we merged in a big planner node change). Once you resolve that ping me and I can re-review!

**Review by p-nayak11 — APPROVED** [review]
Since all merge conflicts are fixed and based on Kevin's previous review, LGTM

**Review by kfu02 — APPROVED** [review]

**Pull request merged**
