### PR TITLE
CI clang_tidy

### PR DESCRIPTION
**Pull request by oswinso**
## Description
This PR adds clang_tidy to CI. To do that:

1. The `test_all` step is broken into a `compile` and `test_all`, since the `clang-tidy` step requires a full compile as well
2. To prevent compiling twice, a `test-soccer-nobuild` and `test-python-nobuild` are introduced which don't compile
3. A `clang-tidy-to-junit.py` script is introduced to convert from `clang_tidy` stdout format to junit xml so that CircleCI can recognize it properly.

### CI shows clang-tidy errors
Two bad changes are introduced in 2385719
```
// main.cpp
Processor* more_bad_changes = new Processor(sim, defendPlus, visionChannel, blueTeam, readLogFile);
```
```
// soccer/ui/MainWindow.cpp
RobotStatusWidget* lmao_unused = (RobotStatusWidget*)_ui.robotStatusList->itemWidget(item);
```

Expected result: [CI](https://app.circleci.com/pipelines/github/RoboJackets/robocup-software/132/workflows/ebe4713b-9b2a-455e-8a72-7347f9d46dc9/jobs/13027/tests) correctly shows `clang_tidy` errors.

### CODE REVIEW

**Review by kylestach — APPROVED** [review]
LGTM

Out of curiosity is converting to junit really the easiest way to deal with tidy errors?

**Comment by oswinso** [comment]
It's like one of two ways of getting CircleCI to show them on the "tests" tab

**Comment by kylestach** [comment]
Gotcha. In that case, this is fine with me.

**Review by JNeiger — APPROVED** [review]
I don't really know this stuff but looks fine to me

**Pull request merged**
