### PR TITLE
Fixed coach crash

### PR DESCRIPTION
**Pull request by jcarn**
fixed small error

oh also it looks like I added some code isn't actually called yet, but it works. I can remove that if needed

### CODE REVIEW

**Comment by jcarn** [comment]
removed the unnecesarry code

**Comment by jgkamat** [comment]
You can just push commits to the jay/coach branch  :P.

I think you lost some changes though, from	77e9625, is that intentional? Other than that, this looks good!

**Comment by jgkamat** [comment]
I can cherry pick the changes made (including the dropped one) into this branch if you want, should I go ahead and do that?

**Comment by jcarn** [comment]
Let's merge this so it doesn't crash, I'll make a new PR or just push straight into yours when my stuff is finished

**Comment by jgkamat** [comment]
I'll move the crash fix into my branch and close this PR, Feel free to push when you're ready :P

**Comment by jgkamat** [comment]
Merged in 337d756

**Pull request closed without merging**
