### PR TITLE
dont use sudo for git submodules

### LINKED ISSUE #642: Make gitsubmodules commands run as normal user and chown all the external directories
Not terribly important. But it be nice to prevent problems in the future that make drastic changes to our submodules. The owners on those are all mixed with root right now.

### PR DESCRIPTION
**Pull request by justbuchanan**
closes #642 

cc @jgkamat

### CODE REVIEW

**Comment by ashaw596** [comment]
Um, I think this will break on most peoples computers if you don't chown everything first and if theres any submodule changes.

**Comment by ashaw596** [comment]
su $(whoami) will also probably come out as su root

**Comment by justbuchanan** [comment]
I tried it out and `su $(whoami)` returns the non-root user.  I was surprised too :)

You're right that people will have to chown before running this though.

**Comment by ashaw596** [comment]
We could throw in a chown $(whoami) in there for a while then so we don't have too many issues if people skip a meeting.

**Comment by justbuchanan** [comment]
Yeah that's not a bad idea.  Just added it.

**Pull request merged**
