### PR TITLE
Manual control implementation

### PR DESCRIPTION
**Pull request by kylestach**
## Description
Very basic manual control.

This PR implements keyboard and gamepad controllers. It creates a new node for managing manual inputs and a new launch configuration for this case. Unlike the old system, we do not (currently) allow hybrid setups where some robots are in manual mode and some robots are controlled by gameplay.

The launch configuration is `manual.launch.py`. It is currently configured for simulation only. Once it is running, you can list the available joysticks as follows:
```
ros2 service call /list_joysticks rj_msgs/srv/ListJoysticks
```

Then, picking from the list, you can assign a joystick to a robot:
```
ros2 service call /select_manual rj_msgs/srv/SetManual '{robot_id: 0, controller_uuid: "keyboard-controller", connect: true}'
```
`"keyboard-controller"` is always available for now.

Eventually this functionality will have a proper UI, but for now, service calls it is.

## Associated Issue
Issues #1147, #1004, #1627

## Design Documents
[Link](link-to-design-doc)

### Keyboard input
1. Fire up `manual.launch.py`
2. Run the service call above for selecting a manual control
3. Make sure the black window has focus
4. Spam w/a/s/d for movement, j/k for kick/chip, up/down arrows to change dribbler power, right/left to change kicker power.

Expected result: the selected robot obeys commands

### CODE REVIEW

**Review by kfu02 — APPROVED** [review]
Works as expected, nicely done. I'd like a way to turn L/R in place (as trying to get smooth motion with only WASD was painful) but I assume that wouldn't be hard to add later.

**Comment by kylestach** [comment]
@kfu02 q/e are turning in place. Also, shift is damped (slow) movement.

**Comment by kfu02** [comment]
Ah okay, makes sense.

**Review by HussainGynai — APPROVED** [review]
LGTM, I guess put in a TODO or issue or something to test the gamepad control at some point.

**Pull request merged**
