### PR TITLE
Delete unused gameplay files + fix test play bug

### PR DESCRIPTION
**Pull request by kfu02**
## Description
Put gameplay in a clean state for upcoming comp. 

**Also, fix test_play/play_selector discrepancy introduced from #1870 . When given a test play, GameplayNode will now override play selector with that test play.**

- delete unused actions (waiting on ROS ActionServer)
- delete outdated plays, tactics, and skills
- add a TODO to update Mark skill (still on old interface)
**- also fixed a mark skill bug**
- fix typing in pass tactic 
- rm MAX_KICK_SPEED file 

## Steps to test
1. Run all working plays. As of 3/29, this includes basic_defense, basic_offense (was basic122 before #1876), and keepaway. (Can do this with test play var in GameplayNode.)

Expected result: All plays behave as expected. No new errors.

### CODE REVIEW

**Comment by kfu02** [comment]
Unused STP files deleted, but not ready for review because I would like to leave comments explaining what some plays that we haven't rewritten should do (so we can rewrite more quickly)

**Review by N8BWert — DISMISSED** [review]
Not sure why, but no matter what play I run it always runs basic_offense.

**Comment by kfu02** [comment]
@N8BWert fixed now

**Review by p-nayak11 — APPROVED** [review]
All working plays ran the way they were supposed to.

**Review by kasohrab — APPROVED** [review]
lgtm

**Pull request merged**
