### PR TITLE
Tutorial walk-through

### PR DESCRIPTION
**Pull request by p-nayak11**
## Description
Will be going through this tutorial as if I do not know anything about the repo (some parts of which I actually don't know anything about :) )

List of things to change in tutorial branch:
1. Make it clear that the ros cli commands need to be in a new sourced terminal while running the sim. 
2. Explain a little more on what "defines" means while looking for the file that publishes the msg for the robot intent topics. 
3. Add to the getting started docs and the tutorial docs that if your terminal setup is unique, you will have to manually install rqt.
4. Add instructions about soccer.launch files, the different CMake files they will need to add to, and give more resources for lambda expressions and arrow operators.

### CODE REVIEW

**Comment by p-nayak11** [comment]
4-wallers

**Comment by p-nayak11** [comment]
File path for the file that defines the message type used by topic  /gameplay/robot_intent/robot_0: **robocup-software/rj_msgs/msg/RobotIntent.msg**

**Comment by p-nayak11** [comment]
Topic /gameplay/robot_intent/robot_0 is a publisher for the /gameplay_node and a subscriber to the /planner node.

**Comment by p-nayak11** [comment]
I finished the dynamic changes of section 5, but I will not post the results on this PR. I will be writing the tutorial for section 6. Either I or someone else will complete this walk-through for that section.

**Comment by kfu02** [comment]
> Topic /gameplay/robot_intent/robot_0 is a publisher for the /gameplay_node and a subscriber to the /planner node.

This is wrong. Remember that nodes publish/subscribe to topics. So gameplay_node publishes RobotIntent messages to robot_intent/robot_0 and planner node subscribes to that topic to get those RobotIntent messages. This can happen at the same time, in real time, thanks to ROS magic. If no nodes were publishing or subscribing to this topic it would still exist (it just wouldn't have any data on it).

Thinking of it like this, it makes sense that another node can subscribe to that same topic, as it's essentially listening in on the topic that gameplay_node is publishing to. In this case robot_intent/robot_0 is actually subscribed to by another node, can you find it?

**Comment by kfu02** [comment]
I believe what I just said is covered by "understanding topics" in the ROS tutorials (already linked to in tutorial) but if you could add that there are 2 nodes subbed to that topic in the tutorial, that would be helpful as a hint.

Screen Shot 2022-07-11 at 6 12 10 PM

**Comment by p-nayak11** [comment]
> > Topic /gameplay/robot_intent/robot_0 is a publisher for the /gameplay_node and a subscriber to the /planner node.
> 
> This is wrong. Remember that nodes publish/subscribe to topics. So gameplay_node publishes RobotIntent messages to robot_intent/robot_0 and planner node subscribes to that topic to get those RobotIntent messages. This can happen at the same time, in real time, thanks to ROS magic. If no nodes were publishing or subscribing to this topic it would still exist (it just wouldn't have any data on it).
> 
> Thinking of it like this, it makes sense that another node can subscribe to that same topic, as it's essentially listening in on the topic that gameplay_node is publishing to. In this case robot_intent/robot_0 is actually subscribed to by another node, can you find it?

Yea, I got the interaction between topics and nodes messed up. I got it now though. I have added the hint to the tutorial. Gameplay node publishes to the /gameplay/robot_intent/robot_0 topic. Control and planner nodes subscribe to /gameplay/robot_intent/robot_0 topic.

**Comment by p-nayak11** [comment]
Screenshot from 2022-07-12 23-40-09
data published to the topic /team_fruit

**Review by kfu02 — APPROVED** [review]
Nice job! There's a few warnings + style errors but it's not a big deal since this won't get merged.

**Pull request closed without merging**
