### PR TITLE
Tuning 11/23

### PR DESCRIPTION
**Pull request by jgkamat**
Bumped min velocity and acceleration, and re-tuned PID controller.

Robots should move a lot faster, but might be a bit out of control.

### CODE REVIEW

**Comment by ashaw596** [comment]
Um,  I'd recommend not raising min velocity. It really suppose to be the
min velocity that prevents the robot from getting stuck. It should not
really be used to speed up the robots. Pid should really be used to
compensate paths being planned faster than the robots are accelerating and
maxacceleration and maxspeed can Increase to plan faster paths. If it's a
constant replanning issue like grabbing the ball, that should be fixed in
the path planning layer.

**Comment by jgkamat** [comment]
Hmm, raising MaxVel was the only thing that seemed to help move the robots faster, anything else (raising p, or velMultipler) seemed to make the robots go out of control. This configuration kept the robots in control while going faster than before. Also, is MaxVel in m/s? 1m/s might be a little small, since the field has grown quite a bit from before. The current config follows the planned path exactly, its just that our planned paths are a bit slow, considering the size of the double field. This is a bit too much, but I'm working on finding a good balance...

**Comment by ashaw596** [comment]
maxVel is in m/s. Yeah maxVel and maxAccel is what tunes our motion planning. I set it to 1 m/s at comp since our motion control was um not very good.

**Comment by ashaw596** [comment]
It used to be like 2.5

**Comment by ashaw596** [comment]
or more like 1.5-2

**Comment by ashaw596** [comment]
My point was that minEffectiveVelocity only affects motion control(ie robots not moving) and only screws up our motion planning and control when therobots are moving or moving slowly..

**Comment by jgkamat** [comment]
oooh you're talking about minEffective, yah I agree I shouldn't be touching that :P 

I'm going to bring that back down to ~0.01/0.02 ish when I'm done.

**Comment by jgkamat** [comment]
Tuning on the shop computer is way better than this, closing.

**Pull request closed without merging**
