### PR TITLE
using std::clamp

### PR DESCRIPTION
**Pull request by ghost**
this uses std::clamp instead of our function which did the same thing

### CODE REVIEW

**Review by kylestach — APPROVED** [review]
LGTM

**Comment by JNeiger** [comment]
I think clamp is only used in one spot in `PacketConvert`, would it be better to just replace that instead of doing this using thing?

**Review by tcontis — APPROVED** [review]
LGTM

**Comment by kylestach** [comment]
This is failing because of mypy issues fixed in #1366. Please pull in changes from `staging` to resolve CI issues.

**Comment by kylestach** [comment]
@JNeiger I think the latest changes address your comments.

**Review by tcontis — APPROVED** [review]

**Comment by kylestach** [comment]
Merging this. Technically @tcontis' review isn't "authorized" as an approval but this was a new member project in which part of the exercise was to do code review.

**Pull request merged**
