### PR TITLE
Replace binutils gatch mirrors with official gnu mirror

### LINKED ISSUE #487: Can't build robot firmware due to gt mirrors being down
I just tried this again on the latest master (90fb3a0f) and it's failing.  @jgkamat, what did you figure out for this?

### PR DESCRIPTION
**Pull request by jgkamat**
Closes #487

Please test this out before you merge though, :smile:  

It LGTM (but so do the old mirrors so idk).

### CODE REVIEW

**Comment by jgkamat** [comment]
This switches our firmware mirror to ftp.gnu.org, which has a higher (lower?) chance of being down? I'm not sure, but the download was faster.

**Comment by jgkamat** [comment]
Coverage is failing because our status token is not present on outside repos. We should find a way to fix that soon...

**Comment by justbuchanan** [comment]
Cool, works on my computer!  And I think your fix for coverage should be fine.

**Comment by jgkamat** [comment]
It's not happy with || true, i'll look into that later, I'll make it true from the makefile for now.

**Comment by justbuchanan** [comment]
LGTM :+1:

**Pull request merged**
